### ISSUE TITLE
Resources are missing.

### ISSUE THREAD

**Issue by ghost** [vbextreme/RigsOfRodsFedora#4]
Resources are not copied to /usr/local/games/ror/, manual moving the folder there fixes the issue.
Setup: Fedora27, build error committed to master ror.

**Comment by vbextreme** [comment]
you have run:
```
sudo ./ror.install
```
In script have line
```
cp -r ./rigs-of-rods/bin/* /usr/local/games/ror/
```

**Comment by ghost** [comment]
The resources folder is located under ./rigs-of-rods/ its content is neede to launch the game. I would suggest to move it to /usr/local/games/ror or making a link.

**Comment by vbextreme** [comment]
if build successfull you got this:
```
vbextreme⠬⠆fedora▶ ~/Sources/rigsofrods/rigs-of-rods/bin ▶ ls
libangelscript_addons.a  plugins.cfg  RoR*
libversion_info.a        resources/   RoRConfig*
```
resources is in bin directory but if fail build you not have this directory

[edit]
the script ror.install, copy all file in local/game

**Comment by ghost** [comment]
Strange, I don't get any errors building, only the resources folder is missing and if I move the resources folder to the right location it starts.

**Comment by vbextreme** [comment]
ok, fix problem
